language: ruby

rvm:
  - 2.6

sudo: enabled

branches:
  only:
    - master

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - echo "skipping tests"

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    region: eu-west-1
    app: dashboard
    env: production
    skip_cleanup: true
    bucket_name: dashboard-versions
    on:
      branch: master
